from __future__ import annotations

VOCAB_BANK = [
    {
        "id": "ja-n5-benkyou",
        "language": "japanese",
        "level": "N5",
        "difficulty": "easy",
        "term": "勉強",
        "reading": "べんきょう / benkyou",
        "question": "「勉強」 nghĩa là gì?",
        "options": {
            "A": "Làm việc",
            "B": "Học tập",
            "C": "Nghỉ ngơi",
            "D": "Đi bộ",
        },
        "answer": "B",
        "meaning_vi": "học tập, việc học",
        "example": "毎日日本語を勉強します。— Mỗi ngày tôi học tiếng Nhật.",
        "explanation": "勉強 thường đi với する thành 勉強する, nghĩa là học hoặc ôn luyện.",
    },
    {
        "id": "ja-n5-toshokan",
        "language": "japanese",
        "level": "N5",
        "difficulty": "easy",
        "term": "図書館",
        "reading": "としょかん / toshokan",
        "question": "「図書館」 nghĩa là gì?",
        "options": {
            "A": "Thư viện",
            "B": "Bệnh viện",
            "C": "Trường học",
            "D": "Nhà ga",
        },
        "answer": "A",
        "meaning_vi": "thư viện",
        "example": "図書館で本を読みます。— Tôi đọc sách ở thư viện.",
        "explanation": "図書館 là địa điểm; trợ từ で dùng cho nơi diễn ra hành động.",
    },
    {
        "id": "ja-n4-yotei",
        "language": "japanese",
        "level": "N4",
        "difficulty": "medium",
        "term": "予定",
        "reading": "よてい / yotei",
        "question": "「予定」 thường có nghĩa là gì?",
        "options": {
            "A": "Dự định/lịch trình",
            "B": "Lý do",
            "C": "Kết quả",
            "D": "Bài kiểm tra",
        },
        "answer": "A",
        "meaning_vi": "dự định, kế hoạch, lịch trình",
        "example": "明日の予定は何ですか。— Lịch ngày mai của bạn là gì?",
        "explanation": "予定 dùng khi nói về điều đã định trước hoặc kế hoạch sắp tới.",
    },
    {
        "id": "en-focus",
        "language": "english",
        "level": "A2/B1",
        "difficulty": "easy",
        "term": "focus",
        "pronunciation": "/ˈfəʊ.kəs/ hoặc /ˈfoʊ.kəs/",
        "question": "`focus` gần nghĩa nhất với từ nào?",
        "options": {
            "A": "concentrate",
            "B": "forget",
            "C": "delay",
            "D": "guess",
        },
        "answer": "A",
        "meaning_vi": "tập trung",
        "collocation": "focus on a task, stay focused",
        "example": "I need to focus on this reading passage.",
        "explanation": "focus on + noun/V-ing là cụm rất hay dùng khi nói về học tập và công việc.",
    },
    {
        "id": "en-consistent",
        "language": "english",
        "level": "B1",
        "difficulty": "medium",
        "term": "consistent",
        "pronunciation": "/kənˈsɪs.tənt/",
        "question": "`consistent` trong học tập nghĩa là gì?",
        "options": {
            "A": "học rất nhanh một lần rồi nghỉ",
            "B": "đều đặn và ổn định",
            "C": "khó hiểu",
            "D": "ngẫu nhiên",
        },
        "answer": "B",
        "meaning_vi": "nhất quán, đều đặn, ổn định",
        "collocation": "consistent effort, consistent practice",
        "example": "Consistent practice is more important than motivation.",
        "explanation": "Từ này hữu ích khi nói về thói quen học: nỗ lực đều đặn thắng cảm hứng nhất thời.",
    },
    {
        "id": "en-review",
        "language": "english",
        "level": "A2/B1",
        "difficulty": "easy",
        "term": "review",
        "pronunciation": "/rɪˈvjuː/",
        "question": "Trong ngữ cảnh học tập, `review` nghĩa là gì?",
        "options": {
            "A": "ôn lại/xem lại",
            "B": "bỏ qua",
            "C": "đoán mò",
            "D": "ngủ quên",
        },
        "answer": "A",
        "meaning_vi": "ôn lại, xem lại",
        "collocation": "review vocabulary, review notes",
        "example": "Review your notes after each study session.",
        "explanation": "Review là bước giúp chuyển kiến thức từ nhớ ngắn hạn sang nhớ dài hạn.",
    },
]
